# Generated by Django 4.2.1 on 2023-11-26 17:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='diary',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.transactiondiary'),
        ),
    ]
