# Generated by Django 4.2.1 on 2023-11-26 17:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0002_rename_title_cryptocurrency_name_and_more'),
        ('accounts', '0002_alter_transaction_diary'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='coin',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='homepage.cryptocurrency'),
        ),
    ]
