# Generated by Django 4.2.1 on 2023-11-26 11:46

import accounts.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_rename_useraccountprofile_userprofile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='avatar',
            field=models.ImageField(default='koteł.jpg', upload_to=accounts.models.user_avatar_image_path),
        ),
    ]
