# Generated by Django 4.2.1 on 2023-11-26 22:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CryptoCryptocurrency',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('short', models.CharField(default='sss', max_length=3)),
                ('country', models.CharField(default=None, max_length=100)),
                ('image', models.ImageField(default=None, upload_to='')),
                ('price_current', models.PositiveIntegerField(default=0)),
                ('price_1h', models.IntegerField(default=0)),
                ('price_1d', models.IntegerField(default=0)),
                ('price_1w', models.IntegerField(default=0)),
                ('price_1m', models.IntegerField(default=0)),
                ('volume', models.PositiveIntegerField(default=0)),
                ('capitalization', models.PositiveIntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='CryptoCryptocurrencyExchange',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('short', models.CharField(default='aaa', max_length=3)),
                ('country', models.CharField(max_length=100)),
                ('image', models.ImageField(upload_to='')),
                ('trust_score', models.PositiveIntegerField()),
                ('volume', models.PositiveIntegerField()),
                ('liqudity', models.PositiveIntegerField(default=None)),
                ('cybersec_score', models.PositiveIntegerField()),
            ],
        ),
    ]
