# Generated by Django 4.2.7 on 2023-11-12 21:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cryptocurrency',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('country', models.CharField(max_length=100)),
                ('image', models.ImageField(upload_to='')),
                ('course_current', models.PositiveIntegerField()),
                ('course_1h', models.IntegerField()),
                ('course_1d', models.IntegerField()),
                ('course_1w', models.IntegerField()),
                ('course_1m', models.IntegerField()),
                ('volume', models.PositiveIntegerField()),
                ('capitalization', models.PositiveIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='CryptocurrencyExchange',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('country', models.CharField(max_length=100)),
                ('image', models.ImageField(upload_to='')),
                ('trust_score', models.PositiveIntegerField()),
                ('volume', models.PositiveIntegerField()),
                ('cybersec_score', models.PositiveIntegerField()),
            ],
        ),
    ]
