# Generated by Django 4.2.1 on 2023-11-26 17:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cryptocurrency',
            old_name='title',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='cryptocurrencyexchange',
            old_name='title',
            new_name='name',
        ),
        migrations.AddField(
            model_name='cryptocurrency',
            name='short',
            field=models.CharField(default='sss', max_length=3),
        ),
        migrations.AddField(
            model_name='cryptocurrencyexchange',
            name='short',
            field=models.CharField(default='aaa', max_length=3),
        ),
    ]
