# Generated by Django 4.2.1 on 2023-11-26 20:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0002_rename_title_cryptocurrency_name_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cryptocurrency',
            old_name='course_1d',
            new_name='price_1d',
        ),
        migrations.RenameField(
            model_name='cryptocurrency',
            old_name='course_1h',
            new_name='price_1h',
        ),
        migrations.RenameField(
            model_name='cryptocurrency',
            old_name='course_1m',
            new_name='price_1m',
        ),
        migrations.RenameField(
            model_name='cryptocurrency',
            old_name='course_1w',
            new_name='price_1w',
        ),
        migrations.RenameField(
            model_name='cryptocurrency',
            old_name='course_current',
            new_name='price_current',
        ),
    ]
