# Generated by Django 4.2.1 on 2023-11-26 20:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0003_rename_course_1d_cryptocurrency_price_1d_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cryptocurrencyexchange',
            name='liqudity',
            field=models.PositiveIntegerField(default=None),
        ),
    ]
